build: support buildargs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,45 +4,52 @@ on:
   workflow_dispatch:
     inputs:
       context:
-        description: 'which context to build'
+        description: "which context to build"
         required: true
       tagname:
-          description: 'tag name'
-          required: true
-
+        description: "tag name"
+        required: true
+      buildargs:
+        description: "docker build args, split by comma"
+        required: false
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-    - name: Log in to GitHub Container Registry
-      uses: docker/login-action@v1
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Validate dockerfile path
-      id: dockerfile_dir
-      run: |
-        if [ ! -f "${{ github.event.inputs.context }}/Dockerfile" ]; then
-          echo "Dockerfile not found at given path"
-          exit 1
-        fi
-        context="${{ github.event.inputs.context }}"
-        echo "::set-output name=image::${context//\//-}"
-
-    - name: build torch image
-      uses: docker/build-push-action@v2
-      with:
-        context: ${{ github.event.inputs.context }}
-        file: ${{ github.event.inputs.context }}/Dockerfile
-        tags: |
-          ghcr.io/${{ github.repository_owner }}/${{ steps.dockerfile_dir.outputs.image }}:${{ github.event.inputs.tagname }}
-        push: true
+      - name: Validate dockerfile path
+        id: dockerfile_dir
+        run: |
+          if [ ! -f "${{ github.event.inputs.context }}/Dockerfile" ]; then
+            echo "Dockerfile not found at given path"
+            exit 1
+          fi
+          context="${{ github.event.inputs.context }}"
+          echo "::set-output name=image::${context//\//-}"
+      - name: Convert build-args
+        id: convert-build-args
+        run: |
+          ARGS=$(echo "${{ github.event.inputs.buildargs }}" | tr ',' '\n')
+          echo "::set-output name=buildargs::${ARGS}"
+      - name: build image
+        uses: docker/build-push-action@v2
+        with:
+          context: ${{ github.event.inputs.context }}
+          file: ${{ github.event.inputs.context }}/Dockerfile
+          tags: |
+            ghcr.io/${{ github.repository_owner }}/${{ steps.dockerfile_dir.outputs.image }}:${{ github.event.inputs.tagname }}
+          push: true
+          build-args: ${{ steps.convert-build-args.outputs.buildargs }}
